Add support for unix domain sockets (APR Protocol)
apache/tomcat pull request #401
Opened 2021-01-15 17:16 UTC by minfrin

Add support and test case for Unix Domain Sockets in
org.apache.coyote.http11.Http11AprProtocol, to support
users using Java versions older than 16.

Requires tomcat-native 1.2.26 and above.

2021-01-15 17:24 UTC, michael-o commented
Give me a couple of days and I will run this on FreeBSD and HP-UX.

2021-01-17 16:46 UTC, rmaucher commented
I still think it is a bad idea to continue to promote the APR connector. At least domain socket support won't be an excuse to keep it around longer than absolutely necessary.

Anyway, if this ends up being included, I will then refactor the feature a bit more.

2021-01-25 20:31 UTC, michael-o requested changes
A few minor issues, but on both FreeBSD and HP-UX the tests with APR 1.6.6 and 1.7.0 passed for me.

2021-01-25 21:05 UTC, minfrin commented on java/org/apache/tomcat/util/net/AprEndpoint.java
> +        String hostname = null;
The APR term is hostname:

http://apr.apache.org/docs/apr/1.7/group__apr__network__io.html#gaa2f399ca2b60b35c0abf7630298c6c9f

So is the underlying getaddrinfo() function: https://en.wikipedia.org/wiki/Getaddrinfo 

I can change it?

2021-01-25 21:11 UTC, minfrin commented on test/org/apache/tomcat/jni/TestUnixDomainSocketServer.java
> +        pool = Pool.create(0);
This is fixed.

2021-01-26 08:29 UTC, michael-o commented on java/org/apache/tomcat/util/net/AprEndpoint.java
> +        String hostname = null;
Leave it that way for consistency, maybe a comment above would help to clarify.

2021-01-26 08:29 UTC, michael-o commented on test/org/apache/tomcat/jni/TestUnixDomainSocketServer.java
> +	private static final String PATH = System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + "tomcat.socket";
Indentation?

2021-01-26 12:41 UTC, minfrin commented on test/org/apache/tomcat/jni/TestUnixDomainSocketServer.java
> +	private static final String PATH = System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + "tomcat.socket";
Fixed.

2021-01-26 12:41 UTC, minfrin commented on java/org/apache/tomcat/util/net/AprEndpoint.java
> +        String hostname = null;
I've added a comment to be clear.

2021-01-26 12:53 UTC, michael-o approved these changes
LGTM. Square, rebase and it is fine for merging.
@rmaucher Can you add your changes in top of these for review after @minfrin has completed his work. We could review and merge them back.

2021-01-26 15:45 UTC, minfrin commented
In theory 96e241c should do the trick, can you confirm this is ready to merge?

2021-01-26 16:12 UTC, michael-o commented
For me yes, but I want Rémy give a chance to do his improvements on top.

2021-01-26 22:11 UTC, rmaucher commented
I don't plan any improvements or changes at this time.

2021-01-26 22:29 UTC, michael-o commented
Alright, I will merge this this week.

2021-01-29 10:44 UTC, minfrin commented
Thanks for this.

2021-02-01 09:35 UTC, michael-o commented
@minfrin I have now pushed this to master. Can you please backport to 9.0.x and 8.5.x and then I will merge them too?

2021-02-01 09:52 UTC, martin-g commented
@michael-o Are new PRs needed ? We can cherry-pick the commits to the other branches

2021-02-01 10:02 UTC, michael-o commented
@martin-g Not really, but I do not fully know which are revelant. I'd rathe merge a complete, blessed set rather then some halfbreed.

2021-02-01 10:09 UTC, martin-g commented
@michael-o You just pushed two commits to master: https://github.com/apache/tomcat/commits/master:
* https://github.com/apache/tomcat/commit/a616bf385a350175a33a0ebf09d8b6688344e9e3 (I guess this is a squashed one)
* https://github.com/apache/tomcat/commit/c4f5e2c9ccd7d65953e3c685d25e436e8330e142

I'd expect only those two to be backported.

2021-02-01 10:25 UTC, michael-o commented
> 
> 
> @michael-o You just pushed two commits to master: https://github.com/apache/tomcat/commits/master:
> 
>     * [a616bf3](https://github.com/apache/tomcat/commit/a616bf385a350175a33a0ebf09d8b6688344e9e3) (I guess this is a squashed one)
> 
>     * [c4f5e2c](https://github.com/apache/tomcat/commit/c4f5e2c9ccd7d65953e3c685d25e436e8330e142)
> 
> 
> I'd expect only those two to be backported.

I tried with 9.0.x and compilation fails, precending commits are missing. That is why I requested a backport from @minfrin.

2021-02-01 11:49 UTC, michael-o commented
> 
> 
> @michael-o You just pushed two commits to master: https://github.com/apache/tomcat/commits/master:
> 
>     * [a616bf3](https://github.com/apache/tomcat/commit/a616bf385a350175a33a0ebf09d8b6688344e9e3) (I guess this is a squashed one)
> 
>     * [c4f5e2c](https://github.com/apache/tomcat/commit/c4f5e2c9ccd7d65953e3c685d25e436e8330e142)
> 
> 
> I'd expect only those two to be backported.

A few fixups will follow, so they need to soak in then someone can cherry pick them to a branch and the squash.

2021-02-01 12:44 UTC, minfrin commented
> @minfrin I have now pushed this to master. Can you please backport to 9.0.x and 8.5.x and then I will merge them too?

On the case, thank you.

2021-02-01 14:41 UTC, minfrin commented
> @minfrin I have now pushed this to master. Can you please backport to 9.0.x and 8.5.x and then I will merge them too?

Backported to 9.0.x, "ant test-apr" passes.

https://github.com/apache/tomcat/pull/402

2021-02-02 16:31 UTC, minfrin commented
> Backported to 9.0.x, "ant test-apr" passes.
> 
> #402

In trying to backport to 8.5.x, there are some further commits needing backporting to address conflicts:

https://github.com/minfrin/tomcat/commit/6945b88b1224b87e6a4ead667a8bb3640974cc03
https://github.com/minfrin/tomcat/commit/e99071f5c235e86e9781e8df9f62709d2e57cc03
https://github.com/minfrin/tomcat/commit/1d108f4ff477354ba065fc99d4f8c781af42bd6c

2021-02-02 16:46 UTC, michael-o commented
Yes, let's do 9.0.x first. @rmaucher has added an acceptable solution for Windows. This should be ported to the `AprEndpoint` too.

2021-05-19 18:33 UTC, markt-asf commented
As far as I can tell, this PR was applied in a616bf38

2021-05-19 18:33 UTC, closed without merging