Improved regexp performance: "a-zA-Z0-9_" -> "\w"
apache/tomcat pull request #592
Opened 2023-02-17 15:53 UTC by tbw777

https://gist.github.com/tbw777/8ce56d2cc3a0216012362d18b7262eb2

2023-02-24 10:36 UTC, markt-asf commented on java/jakarta/servlet/jsp/resources/jspxml.xsd
> +<!ENTITY AsciiName    "[\w-]*">
The Tomcat project is unable to change these schema. We have to use the ones provided by the specification. Please direct this part of the PR to the Jakarta Schema project:
https://github.com/eclipse-ee4j/jakartaee-schemas

2023-02-24 10:37 UTC, markt-asf requested changes
Thanks for the performance data. That is really useful.
Once the PR is updated to remove the schema changes, I think this will be ready to merge.

2023-02-24 12:41 UTC, ChristopherSchultz commented
I'm curious about performance data when the `\w` has other things added to it, which is the case for all examples in Tomcat. This microbenchmark only compares `[A-Za-z0-9_]` as the whole character class against `\w` and `[\w]` without any other characters added to the character class.

Also, most expressions used in Tomcat have a trailing `+` which in the attached performance data show that performance is again terrible. It still appears measurably and consistently better than `[A-Za-z0-9_]` but I think it's important to benchmark what Tomcat _actually_ uses and not something _very close_ to what Tomcat uses.

2023-02-24 21:12 UTC, tbw777 commented
https://gist.github.com/tbw777/cd394ec67a01f9e7e8fe4d0c66d74637

2023-02-24 22:41 UTC, ChristopherSchultz commented
Thanks @tbw777 for the updated micro-benchmarks. I agree that the performance improvement is significant enough to warrant a change to Tomcat.

2023-02-25 07:14 UTC, tbw777 commented
Compile speed
https://gist.github.com/tbw777/6a6303f64894e65a160d3f6321685d27

2023-03-10 07:29 UTC, aooohan commented
Merge manually, thanks.

2023-03-10 07:29 UTC, closed without merging